apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: shop-app
type: Opaque
data:
  username: cm9vdA==          # echo -n "root" | base64
  password: bWNsQDIwMjU=      # echo -n "mcl@2025" | base64
  root-password: bWNsQDIwMjU= # same as password (root user)