apiVersion: batch/v1
kind: Job
metadata:
  name: laravel-migrate
  namespace: shop-app
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: mudhihirdocker/smart-inventory:latest
          command: ["sh", "-c", "php artisan migrate --force"]
          env:
            - name: DB_HOST
              value: mysql-service
            - name: DB_PORT
              value: "3306"
            - name: DB_DATABASE
              value: simu_inventory
            - name: DB_USERNAME
              value: root
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: root-password