apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: shop-app
type: Opaque
data:
  username: c2hvcF91c2Vy
  password: c2VjdXJlX3Bhc3N3b3Jk
  root-password: cm9vdF9wYXNzd29yZA==
---
apiVersion: v1
kind: Secret
metadata:
  name: mail-secret
  namespace: shop-app
type: Opaque
data:
  username: eW91cmVtYWlsQGdtYWlsLmNvbQ==
  password: eW91cmFwcHBhc3N3b3Jk