// @ts-nocheck
import React, { createContext, useState, useContext, ReactNode, useEffect } from 'react';

export type Language = 'sw' | 'en' | 'zh';

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  sw: {
    // ===== GENERAL =====
    app_name: 'IMS',
    dashboard: 'Dashibodi',
    logged_in_as: 'Umeingia kama',
    register_user: 'Sajili mtumiaji',
    admins: 'Wasimamizi',
    suppliers: 'Wasambazaji',
    customers: 'Wateja',
    deliveries: 'Wasafirishaji',
    orders: 'Oda',
    revenue: 'Mapato',
    stock: 'Akiba',
    cart: 'Kikapu',
    my_orders: 'Oda zangu',
    logout: 'Toka',
    login: 'Ingia',
    email: 'Barua pepe',
    password: 'Nenosiri',
    demo: 'Demo — chagua akaunti',
    checkout_success: 'Oda yako imepokewa. Unaweza kufuatilia hali yake hapa chini.',
    total: 'Jumla',
    delivery_fee: 'Nauli ya pikipiki',
    confirm_order: 'Thibitisha oda',
    search: 'Tafuta bidhaa...',
    add_to_cart: 'Ongeza kwenye kikapu',
    add_more: 'Ongeza tena',
    order_status: 'Hali ya oda',
    order_id: 'Oda #',
    rider: 'Msafirishaji',
    no_orders: 'Huna oda bado.',
    paid: 'Imelipwa',
    unpaid: 'Haijalipwa',
    pending_approval: 'Inasubiri idhini',
    active: 'Hai',
    deleted: 'Imefutwa',
    approve: 'Idhinisha',
    completed: 'Imekamilika',
    in_progress: 'Inaendelea',
    status_steps: ['Imepokewa', 'Inaandaliwa sokoni', 'Ipo njiani', 'Imefika'] as any,
    forgot_password: 'Umesahau nenosiri?',
    reset_password: 'Weka upya nenosiri',
    enter_email_reset: 'Weka barua pepe yako ili kupokea kiungo cha kuweka upya nenosiri.',
    send_reset_link: 'Tuma kiungo cha kuweka upya',
    back_to_login: 'Rudi kwenye kuingia',
    reset_link_sent: 'Kiungo cha kuweka upya nenosiri kimetumwa kwa barua pepe yako.',
    overview_title: 'Dashibodi',
    recent_activity: 'Shughuli za hivi karibuni',
    total_revenue: 'Jumla ya mapato',
    all_orders: 'Oda zote',
    active_suppliers: 'Wasambazaji hai',
    total_deliveries: 'Wasafirishaji',
    suppliers_count: 'Wasambazaji',
    customers_count: 'Wateja',
    pending_approval_count: 'Wanasubiri idhini',
    paid_orders: 'Oda zilizolipwa',
    unpaid_orders: 'Zinasubiri malipo',
    avg_order_value: 'Wastani wa oda',
    assigned_orders: 'Oda zilizopangiwa',
    completed_orders: 'Zimekamilika',
    ongoing_orders: 'Zinaendelea',
    register_title: 'Sajili mtumiaji mpya',
    user_type: 'Aina ya mtumiaji',
    full_name: 'Jina kamili',
    register_btn: 'Sajili mtumiaji',
    register_success: 'Mtumiaji amesajiliwa. Taarifa za kuingia zitatumwa kwa barua pepe.',
    name_col: 'Jina',
    email_col: 'Barua pepe',
    role_col: 'Role',
    status_col: 'Hali',
    phone_col: 'Simu',
    orders_count_col: 'Idadi ya oda',
    total_spent_col: 'Jumla matumizi',
    action_col: 'Kitendo',
    order_number_col: 'Namba',
    creating: 'Inaunda...',
    updating: 'Inasasisha...',
    customer_col: 'Mteja',
    amount_col: 'Kiasi',
    payment_col: 'Malipo',
    rider_col: 'Rider',
    admins_title: 'Wasimamizi (Admin, Manager na Mhasibu)',
    suppliers_title: 'Wasambazaji',
    deliveries_title: 'Wasafirishaji (Pikipiki)',
    assigned_orders_col: 'Oda alizopangiwa',
    completed_deliveries_col: 'Zilizokamilika',
    customers_title: 'Wateja',
    orders_title: 'Oda zote',
    my_orders_title: 'Oda zangu',
    revenue_title: 'Ripoti za mapato',
    revenue_total: 'Mapato jumla (yaliyolipwa)',
    revenue_paid: 'Oda zilizolipwa',
    revenue_unpaid: 'Oda zinazosubiri malipo',
    revenue_chart_title: 'Mapato ya miezi 6 iliyopita',
    revenue_month: 'Mwezi',
    revenue_amount: 'Mapato',
    shop_title: 'Sokoni — bidhaa zote',
    cart_title: 'Kikapu changu',
    cart_empty: 'Kikapu chako hakina kitu bado.',
    customer_orders_title: 'Oda zangu',
    customer_no_orders: 'Huna oda bado.',
    users_title: 'Orodha ya watumiaji',
    add_user: 'Ongeza mtumiaji',
    close: 'Funga',
    self_register: 'Jisajili kama mteja',
    register_customer_title: 'Jisajili kama mteja',
    phone: 'Namba ya simu',
    register: 'Jisajili',
    already_have_account: 'Tayari una akaunti? Ingia',
    customer_registered: 'Usajili wako umefanikiwa. Unaingia moja kwa moja...',
    search_table: 'Tafuta...',
    previous: 'Awali',
    next: 'Inayofuata',
    refresh: 'Weka upya',
    showing: 'Inaonyesha',
    of: 'kati ya',
    entries: 'safu',
    no_results: 'Hakuna matokeo',
    or_continue_with: 'Au endelea na',
    signin_google: 'Ingia kwa Google',
    signin_apple: 'Ingia kwa Apple',
    items_per_page: 'Safu kwa ukurasa',
    settings: 'Mipangilio', // ✅ Swahili

    // ===== DASHBOARD CARDS & CHARTS =====
    total_users: 'Jumla ya Watumiaji',
    total_shops: 'Jumla ya Maduka',
    products_in_stock: 'Bidhaa Zilizo Akiba',
    total_sales: 'Jumla ya Mauzo',
    total_companies: 'Jumla ya Makampuni',
    returned_devices: 'Vifaa Vilivyorejeshwa',
    products_by_category: 'Bidhaa kwa Kategoria',
    products_by_status: 'Bidhaa kwa Hali',
    sales_by_payment_method: 'Mauzo kwa Njia ya Malipo',
    top_selling_products: 'Bidhaa Zinazouzwa Sana',
    sales_trend_30_days: 'Mwenendo wa Mauzo (Siku 30 zilizopita)',
    sales_by_month: 'Mauzo kwa Mwezi',
    product: 'Bidhaa',
    count: 'Idadi',
    total_amount: 'Jumla ya Kiasi',
    loading_dashboard: 'Inapakia dashibodi...',
    error_loading_dashboard: 'Hitilafu wakati wa kupakia dashibodi',
    retry: 'Jaribu tena',

    // ===== SALES PAGE =====
    sales: 'Mauzo',
    sales_history: 'Historia ya Mauzo',
    all_statuses: 'Hali Zote',
    filter_by_status: 'Chuja kwa Hali',
    make_sale: 'FanyaMauzo',
    sku: 'SKU',
    imei: 'IMEI',
    shop: 'Duka',
    payment_method: 'Njia ya Malipo',
    cash: 'Pesa Taslimu',
    loan: 'Mkopo',
    loan_price: 'Bei ya Mkopo',
    select_loan_price: 'Chagua Bei ya Mkopo',
    no_loan_prices: 'Hakuna Bei za Mikopo',
    discount_amount: 'Kiasi cha Punguzo',
    confirm_sale: 'Thibitisha Mauzo',
    product_details: 'Maelezo ya Bidhaa',
    cash_selling_price: 'Bei ya Kuuza Pesa Taslimu',
    loan_selling_prices: 'Bei za Mikopo',
    status: 'Hali',
    stock_status: 'Hali ya Akiba',
    agent: 'Wakala',
    company: 'Kampuni',
    cancellation_reason: 'Sababu ya Kughairi',
    created_at: 'Imeundwa Tarehe',
    cancel_sale: 'Ghairi Mauzo',
    restore: 'Rejesha',
    provide_cancellation_reason: 'Tafadhali toa sababu ya kughairi',
    enter_reason: 'Weka sababu',
    confirm_cancel: 'Thibitisha Kughairi',
    analysis: 'Uchambuzi',

    // ===== REPORTS PAGE =====
    reports: 'Ripoti',
    export_csv: 'Hamisha CSV',
    export_excel: 'Hamisha Excel',
    exporting: 'Inahamisha...',
    sales_report: 'Ripoti ya Mauzo',
    stock_report: 'Ripoti ya Akiba',
    returns_report: 'Ripoti ya Marejesho',
    from_date: 'Kuanzia Tarehe',
    to_date: 'Hadi Tarehe',
    select_agent: 'Chagua Wakala',
    category: 'Kategoria',
    all_categories: 'Kategoria Zote',
    all_shops: 'Maduka Yote',
    all: 'Zote',
    select_stock_status: 'Chagua Hali ya Akiba',
    updated_at: 'Imesasishwa Tarehe',
    buying_price: 'Bei ya Kununua',
    total_profit: 'Faida Jumla',
    total_products: 'Jumla ya Bidhaa',
    pending_return: 'Inasubiri Kurejeshwa',
    total_returned: 'Jumla ya Zilizorejeshwa',
    sold: 'Imeuzwa',

    // ===== PROFILE & OTP KEYS =====
    profile: 'Wasifu',
    edit_profile: 'Hariri wasifu',
    update_profile: 'Sasisha wasifu',
    change_password: 'Badilisha nenosiri',
    current_password: 'Nenosiri la sasa',
    new_password: 'Nenosiri mpya',
    confirm_password: 'Thibitisha nenosiri',
    verify_otp_title: 'Thibitisha OTP',
    otp_code: 'Msimbo wa OTP',
    resend_otp: 'Tuma OTP tena',
    enter_otp_sent: 'Ingiza msimbo wa OTP uliotumwa kwa',
    enter_otp_and_new_password: 'Ingiza msimbo wa OTP na nenosiri mpya',
    verify: 'Thibitisha',
    loading: 'Inapakia...',
    verified: 'Imethibitishwa',
    pending: 'Inasubiri',

    // ===== PRODUCT CATEGORIES =====
    product_categories: 'Kategoria za Bidhaa',
    add_category: 'Ongeza Kategoria',
    edit_category: 'Hariri Kategoria',
    delete_category: 'Futa Kategoria',
    delete_category_confirm: 'Je, una uhakika unataka kufuta kategoria ?',
    category_name: 'Jina la Kategoria',
    model: 'Modeli',
    enter_sku: 'Weka SKU',
    add: 'Ongeza',
    toggle_status: 'Badilisha Hali',
    activate_category_confirm: 'Je, una uhakika unataka kuwezesha kategoria ?',
    deactivate_category_confirm: 'Je, una uhakika unataka kuzima kategoria ?',

    // ===== SHOPS =====
    shops: 'Maduka',
    add_shop: 'Ongeza Duka',
    edit_shop: 'Hariri Duka',
    create_shop: 'Unda Duka',
    delete_shop: 'Futa Duka',
    delete_shop_confirm: 'Je, una uhakika unataka kufuta duka ?',
    restore_shop: 'Rejesha Duka',
    restore_shop_confirm: 'Je, una uhakika unataka kurejesha duka ?',
    force_delete_shop: 'Futa Duka Kabisa',
    force_delete_shop_confirm: 'Je, una uhakika unataka kufuta duka  kabisa? Kitendo hiki hakiwezi kugeuzwa.',
    shop_name: 'Jina la Duka',
    location: 'Mahali',
    manager: 'Meneja',
    select_manager: 'Chagua Meneja',
    change_status: 'Badilisha Hali',
    maintenance: 'Matengenezo',
    inactive: 'Haifanyi Kazi',

    // ===== ROLES & PERMISSIONS =====
    roles: 'Majukumu',
    permissions: 'Ruhusa',
    add_role: 'Ongeza jukumu',
    edit_role: 'Hariri jukumu',
    create_role: 'Unda jukumu',
    delete_role: 'Futa jukumu',
    delete_role_confirm: 'Je, una uhakika unataka kufuta jukumu la "{{name}}"?',
    role_name: 'Jina la jukumu',
    display_name: 'Jina linaloonyeshwa',
    description: 'Maelezo',
    users_count: 'Idadi ya watumiaji',
    manage_permissions: 'Simamia ruhusa',
    search_roles: 'Tafuta majukumu...',
    no_roles: 'Hakuna majukumu yaliyopatikana',
    add_permission: 'Ongeza ruhusa',
    edit_permission: 'Hariri ruhusa',
    create_permission: 'Unda ruhusa',
    delete_permission: 'Futa ruhusa',
    delete_permission_confirm: 'Je, una uhakika unataka kufuta ruhusa ya "{name}"?',
    permission_name: 'Jina la ruhusa',
    search_permissions: 'Tafuta ruhusa...',
    no_permissions: 'Hakuna ruhusa zilizopatikana',
    save: 'Hifadhi',
    update: 'Sasisha',
    create: 'Unda',
    cancel: 'Ghairi',

    // ===== AUDIT TRAIL =====
    audit_trail: 'Rekodi ya Ufuatiliaji',
    date_time: 'Tarehe na Saa',
    user: 'Mtumiaji',
    action: 'Kitendo',
    module: 'Moduli',
    total_entries: 'Jumla ya Rekodi',
    today: 'Leo',
    this_week: 'Wiki Hii',
    unique_modules: 'Moduli za Kipekee',
    all_modules: 'Moduli Zote',
    all_actions: 'Vitendo Vyote',
    user_email: 'Barua pepe ya Mtumiaji',
    enter_user_email: 'Weka barua pepe ya mtumiaji',
    search_in_audit: 'Tafuta katika rekodi...',

    // ===== FAILED LOGINS =====
    failed_logins: 'Majaribio ya Kuingia Yaliyoshindwa',
    total_records: 'Jumla ya Rekodi',
    unique_emails: 'Barua Pepe za Kipekee',
    unique_ips: 'IP za Kipekee',
    blocked_ips: 'IP Zilizozuiliwa',
    today_attempts: 'Majaribio ya Leo',
    attempts: 'Majaribio',
    last_attempt: 'Jaribio la Mwisho',
    blocked: 'Imezuiwa',
    block_ip: 'Zuia IP',
    unblock_ip: 'Ondoa Zuio la IP',
    clear_attempts: 'Futa Majaribio',
    clear_all: 'Futa Zote',
    clear_email_confirm: 'Je, una uhakika unataka kufuta majaribio yote ya ?',
    clear_all_confirm: 'Je, una uhakika unataka kufuta rekodi zote za majaribio ya kuingia yaliyoshindwa?',
    block_ip_confirm: 'Je, una uhakika unataka kuzuia IP ?',
    unblock_ip_confirm: 'Je, una uhakika unataka kuondoa zuio la IP ?',

    // ===== COMPANIES =====
    companies: 'Makampuni',
    add_company: 'Ongeza Kampuni',
    edit_company: 'Hariri Kampuni',
    delete_company: 'Futa Kampuni',
    delete_company_confirm: 'Je, una uhakika unataka kufuta kampuni ?',
    restore_company: 'Rejesha Kampuni',
    restore_company_confirm: 'Je, una uhakika unataka kurejesha kampuni ?',
    force_delete_company: 'Futa Kampuni Kabisa',
    force_delete_company_confirm: 'Je, una uhakika unataka kufuta kampuni  kabisa? Kitendo hiki hakiwezi kugeuzwa.',
    activate_company_confirm: 'Je, una uhakika unataka kuwezesha kampuni ?',
    deactivate_company_confirm: 'Je, una uhakika unataka kuzima kampuni ?',
    company_name: 'Jina la Kampuni',
    address: 'Anwani',
    trashed: 'Zilizofutwa',
    actions: 'Vitendo',
    edit: 'Hariri',
    force_delete: 'Futa Kabisa',
    delete: 'Futa',
    confirm: 'Thibitisha',
    access_denied: 'Hakuna Ruhusa',
    you_do_not_have_permission: 'Huna ruhusa ya kuona makampuni.',

    // ===== USERS =====
    users: 'Watumiaji',
    create_user: 'Unda mtumiaji',
    edit_user: 'Hariri mtumiaji',
    delete_user: 'Futa mtumiaji',
    delete_user_confirm: 'Je, una uhakika unataka kufuta mtumiaji ?',
    default_password: 'Nenosiri chaguo-msingi',
    verify_user: 'Thibitisha Mtumiaji',
    verified_col: 'Imethibitishwa',
    activate: 'Wezesha',
    deactivate: 'Zima',
    suspend: 'Simamisha',
    assign_role: 'Panga jukumu',
    assign_role_to: 'Panga jukumu kwa',
    reset_password_for: 'Weka upya nenosiri la',
    verify_now: 'Thibitisha sasa',
    suspended: 'Imesimamishwa',
    yes: 'Ndio',
    no: 'Hapana',
    select_role: '-- Chagua jukumu --',

    // ===== OTP MANAGEMENT =====
    otp_management: 'Usimamizi wa OTP',
    type: 'Aina',
    used: 'Imetumika',
    unused: 'Haijatumika',
    expired: 'Imeisha muda',
    expires_at: 'Inaisha Muda',
    enter_email: 'Weka barua pepe',
    all_types: 'Aina Zote',
    all_status: 'Hali Zote',
    cleanup_expired: 'Futa Zilizoisha Muda',
    cleanup_used: 'Futa OTP Zilizotumika',
    cleanup_expired_confirm: 'Je, una uhakika unataka kufuta rekodi zote za OTP zilizoisha muda?',
    cleanup_used_confirm: 'Je, una uhakika unataka kufuta rekodi zote za OTP zilizotumika zaidi ya siku 30?',

    // ===== PRODUCTS =====
    products: 'Bidhaa',
    add_product: 'Ongeza Bidhaa',
    edit_product: 'Hariri Bidhaa',
    delete_product: 'Futa Bidhaa',
    delete_product_confirm: 'Je, una uhakika unataka kufuta bidhaa yenye IMEI {imei}?',
    restore_product: 'Rejesha Bidhaa',
    restore_product_confirm: 'Je, una uhakika unataka kurejesha bidhaa yenye IMEI {imei}?',
    force_delete_product: 'Futa Bidhaa Kabisa',
    force_delete_product_confirm: 'Je, una uhakika unataka kufuta bidhaa yenye IMEI {imei} kabisa? Kitendo hiki hakiwezi kugeuzwa.',
    change_product_status: 'Badilisha Hali ya Bidhaa',
    current_status: 'Hali ya sasa',
    no_loan_prices_added: 'Hakuna bei za mikopo zilizoongezwa',
    in_stock: 'Ipo Akiba',
    transferred: 'Imehamishwa',
    received: 'Imepokelewa',
    returned: 'Imerejeshwa',
    select_sku: 'Chagua SKU',
    select_company: 'Chagua Kampuni',
    select_category_first: 'Chagua kategoria kwanza',
    no_skus_for_category: 'Hakuna SKU za kategoria hii',
    imei_list: 'Orodha ya IMEI',
    add_imei: 'Ongeza IMEI',
    scan: 'Changanua',
    single_imei: 'IMEI moja',
    pricing: 'Bei',
    basic_information: 'Taarifa za Msingi',
    purchase_info: 'Taarifa za Ununuzi',
    unit_price: 'Bei ya Kitengo',
    purchased: 'Imeununuliwa',
    added: 'Imeongezwa',
    available: 'Inapatikana',
    no_more_items: 'Hakuna bidhaa zaidi inapatikana',
    show_purchase_history: 'Onyesha historia ya ununuzi',
    hide_history: 'Ficha historia',
    auto_filled: 'Imejazwa kiotomatiki',
    enter_imei_manually: 'Ingiza IMEI mwenyewe',
    please_enter_imei: 'Tafadhali ingiza IMEI',
    imei_already_exists: 'IMEI "{imei}" tayari ipo kwenye orodha',
    imei_added: 'IMEI "{imei}" imeongezwa',
    imei_updated: 'IMEI imesasishwa kuwa "{imei}"',
    imei_scanned_and_added: 'IMEI "{imei}" imechanganuliwa na kuongezwa',
    product_updated_successfully: 'Bidhaa imesasishwa kwa mafanikio',
    products_created: 'Bidhaa zimeundwa kwa mafanikio',
    stop_scanner: 'Simama Scanner',
    scanner_init_error: 'Hitilafu ya kuanzisha scanner',
    could_not_start_camera: 'Haikuweza kuanza kamera',
    camera_permission_denied: 'Ruhusa ya kamera imekataliwa. Tafadhali ruhusu kamera kwenye mipangilio ya kivinjari chako.',
    no_camera_found: 'Hakuna kamera iliyopatikana kwenye kifaa hiki.',
    scanner_element_not_found: 'Kipengele cha scanner hakipatikani. Tafadhali jaribu tena.',
    duplicate_imei_warning: 'IMEI "{imei}" tayari ipo kwenye orodha',
    select_status: 'Chagua Hali',

    // ===== ANALYSIS PAGE =====
    analysis_dashboard: 'Dashibodi ya Uchambuzi',
    daily_trend_30d: 'Mwenendo wa Siku 30',
    weekly_trend: 'Mwenendo wa Wiki',
    monthly_trend: 'Mwenendo wa Mwezi',
    revenue_by_category: 'Mapato kwa Kategoria',
    top_agents_by_revenue: 'Mawakala Bora kwa Mapato',
    top_shops_by_revenue: 'Maduka Bora kwa Mapato',
    top_products_by_revenue: 'Bidhaa Bora kwa Mapato',
    top_models_by_revenue: 'Modeli Bora kwa Mapato',
    profit_trends: 'Mwenendo wa Faida',
    interest_summary: 'Muhtasari wa Riba',
    total_loan_sales: 'Jumla ya Mauzo ya Mikopo',
    total_loan_revenue: 'Jumla ya Mapato ya Mikopo',
    interest_earned: 'Riba Iliyopatikana',
    total_cash_sales: 'Jumla ya Mauzo ya Pesa Taslimu',
    total_cash_revenue: 'Jumla ya Mapato ya Pesa Taslimu',
    total_stock_cost: 'Gharama Jumla ya Akiba',
    stock_summary: 'Muhtasari wa Akiba',
    agent_ranking_by_sales: 'Orodha ya Mawakala kwa Mauzo',
    rank: 'Nafasi',
    loading_analysis: 'Inapakia uchambuzi...',
    error_loading_analysis: 'Hitilafu wakati wa kupakia uchambuzi',
  },

  en: {
    // ===== GENERAL =====
    app_name: 'IMS',
    dashboard: 'Dashboard',
    logged_in_as: 'Logged in as',
    register_user: 'Register user',
    admins: 'Admins',
    suppliers: 'Suppliers',
    customers: 'Customers',
    deliveries: 'Deliveries',
    orders: 'Orders',
    revenue: 'Revenue',
    stock: 'Stock',
    cart: 'Cart',
    my_orders: 'My orders',
    logout: 'Logout',
    login: 'Login',
    email: 'Email',
    password: 'Password',
    demo: 'Demo — select an account',
    checkout_success: 'Your order has been received. You can track its status below.',
    total: 'Total',
    delivery_fee: 'Delivery fee',
    confirm_order: 'Confirm order',
    search: 'Search products...',
    add_to_cart: 'Add to cart',
    add_more: 'Add more',
    order_status: 'Order status',
    order_id: 'Order #',
    rider: 'Rider',
    no_orders: 'You have no orders yet.',
    paid: 'Paid',
    unpaid: 'Unpaid',
    pending_approval: 'Pending approval',
    active: 'Active',
    deleted: 'Deleted',
    approve: 'Approve',
    completed: 'Completed',
    in_progress: 'In progress',
    status_steps: ['Received', 'Being prepared', 'On the way', 'Delivered'] as any,
    forgot_password: 'Forgot password?',
    reset_password: 'Reset password',
    enter_email_reset: 'Enter your email to receive a password reset link.',
    send_reset_link: 'Send reset link',
    back_to_login: 'Back to login',
    reset_link_sent: 'A password reset link has been sent to your email.',
    overview_title: 'Dashboard',
    recent_activity: 'Recent activity',
    total_revenue: 'Total revenue',
    all_orders: 'All orders',
    active_suppliers: 'Active suppliers',
    total_deliveries: 'Deliveries',
    suppliers_count: 'Suppliers',
    customers_count: 'Customers',
    pending_approval_count: 'Pending approval',
    paid_orders: 'Paid orders',
    unpaid_orders: 'Unpaid orders',
    avg_order_value: 'Average order value',
    assigned_orders: 'Assigned orders',
    completed_orders: 'Completed',
    ongoing_orders: 'Ongoing',
    register_title: 'Register new user',
    user_type: 'User type',
    full_name: 'Full name',
    register_btn: 'Register user',
    register_success: 'User registered. Login details will be sent to their email.',
    name_col: 'Name',
    email_col: 'Email',
    role_col: 'Role',
    status_col: 'Status',
    phone_col: 'Phone',
    orders_count_col: 'Orders count',
    total_spent_col: 'Total spent',
    action_col: 'Action',
    order_number_col: 'Order #',
    customer_col: 'Customer',
    amount_col: 'Amount',
    payment_col: 'Payment',
    rider_col: 'Rider',
    admins_title: 'Admins (Admin, Manager & Accountant)',
    suppliers_title: 'Suppliers',
    deliveries_title: 'Deliveries (Riders)',
    assigned_orders_col: 'Assigned orders',
    completed_deliveries_col: 'Completed',
    customers_title: 'Customers',
    orders_title: 'All orders',
    my_orders_title: 'My orders',
    revenue_title: 'Revenue reports',
    revenue_total: 'Total revenue (paid)',
    revenue_paid: 'Paid orders',
    revenue_unpaid: 'Unpaid orders',
    revenue_chart_title: 'Revenue over the last 6 months',
    revenue_month: 'Month',
    revenue_amount: 'Revenue',
    shop_title: 'Shop — all products',
    cart_title: 'My cart',
    cart_empty: 'Your cart is empty.',
    customer_orders_title: 'My orders',
    customer_no_orders: 'You have no orders yet.',
    users_title: 'User list',
    add_user: 'Add user',
    close: 'Close',
    self_register: 'Register as customer',
    register_customer_title: 'Register as customer',
    phone: 'Phone number',
    register: 'Register',
    already_have_account: 'Already have an account? Login',
    customer_registered: 'Registration successful. You are being logged in...',
    search_table: 'Search...',
    previous: 'Previous',
    next: 'Next',
    refresh: 'Refresh',
    showing: 'Showing',
    of: 'of',
    entries: 'entries',
    no_results: 'No results',
    or_continue_with: 'Or continue with',
    signin_google: 'Sign in with Google',
    signin_apple: 'Sign in with Apple',
    items_per_page: 'Items per page',
    settings: 'Settings', // ✅ English

    // ===== DASHBOARD CARDS & CHARTS =====
    total_users: 'Total Users',
    total_shops: 'Total Shops',
    products_in_stock: 'Products In Stock',
    total_sales: 'Total Sales',
    total_companies: 'Total Companies',
    returned_devices: 'Returned Devices',
    products_by_category: 'Products by Category',
    products_by_status: 'Products by Status',
    sales_by_payment_method: 'Sales by Payment Method',
    top_selling_products: 'Top Selling Products',
    sales_trend_30_days: 'Sales Trend (Last 30 Days)',
    sales_by_month: 'Sales by Month',
    product: 'Product',
    count: 'Count',
    total_amount: 'Total Amount',
    loading_dashboard: 'Loading dashboard...',
    error_loading_dashboard: 'Error loading dashboard',
    retry: 'Retry',

    // ===== SALES PAGE =====
    sales: 'Sales',
    sales_history: 'Sales History',
    all_statuses: 'All Statuses',
    filter_by_status: 'Filter by Status',
    make_sale: 'MakeSale',
    sku: 'SKU',
    imei: 'IMEI',
    shop: 'Shop',
    payment_method: 'Payment Method',
    cash: 'Cash',
    loan: 'Loan',
    loan_price: 'Loan Price',
    select_loan_price: 'Select Loan Price',
    no_loan_prices: 'No Loan Prices',
    discount_amount: 'Discount Amount',
    confirm_sale: 'Confirm Sale',
    product_details: 'Product Details',
    cash_selling_price: 'Cash Selling Price',
    loan_selling_prices: 'Loan Selling Prices',
    status: 'Status',
    stock_status: 'Stock Status',
    agent: 'Agent',
    company: 'Company',
    cancellation_reason: 'Cancellation Reason',
    created_at: 'Created At',
    cancel_sale: 'Cancel Sale',
    restore: 'Restore',
    provide_cancellation_reason: 'Please provide a reason for cancellation',
    enter_reason: 'Enter reason',
    confirm_cancel: 'Confirm Cancel',
    analysis: 'Analysis',

    // ===== REPORTS PAGE =====
    reports: 'Reports',
    export_csv: 'Export CSV',
    export_excel: 'Export Excel',
    exporting: 'Exporting...',
    sales_report: 'Sales Report',
    stock_report: 'Stock Report',
    returns_report: 'Returns Report',
    from_date: 'From Date',
    to_date: 'To Date',
    select_agent: 'Select Agent',
    category: 'Category',
    all_categories: 'All Categories',
    all_shops: 'All Shops',
    all: 'All',
    select_stock_status: 'Select Stock Status',
    updated_at: 'Updated At',
    buying_price: 'Buying Price',
    total_profit: 'Total Profit',
    total_products: 'Total Products',
    pending_return: 'Pending Return',
    total_returned: 'Total Returned',
    sold: 'Sold',

    // ===== PROFILE & OTP KEYS =====
    profile: 'Profile',
    edit_profile: 'Edit profile',
    update_profile: 'Update profile',
    change_password: 'Change password',
    current_password: 'Current password',
    new_password: 'New password',
    confirm_password: 'Confirm password',
    verify_otp_title: 'Verify OTP',
    otp_code: 'OTP code',
    resend_otp: 'Resend OTP',
    enter_otp_sent: 'Enter the OTP code sent to',
    enter_otp_and_new_password: 'Enter the OTP code and your new password',
    verify: 'Verify',
    loading: 'Loading...',
    verified: 'Verified',
    pending: 'Pending',
    creating: 'Creating...',
    updating: 'Updating...',

    // ===== PRODUCT CATEGORIES =====
    product_categories: 'Product Categories',
    add_category: 'Add Category',
    edit_category: 'Edit Category',
    delete_category: 'Delete Category',
    delete_category_confirm: 'Are you sure you want to delete category ?',
    category_name: 'Category Name',
    model: 'Model',
    enter_sku: 'Enter SKU',
    add: 'Add',
    toggle_status: 'Toggle Status',
    activate_category_confirm: 'Are you sure you want to activate category ?',
    deactivate_category_confirm: 'Are you sure you want to deactivate category ?',

    // ===== SHOPS =====
    shops: 'Shops',
    add_shop: 'Add Shop',
    edit_shop: 'Edit Shop',
    create_shop: 'Create Shop',
    delete_shop: 'Delete Shop',
    delete_shop_confirm: 'Are you sure you want to delete shop ?',
    restore_shop: 'Restore Shop',
    restore_shop_confirm: 'Are you sure you want to restore shop ?',
    force_delete_shop: 'Permanently Delete Shop',
    force_delete_shop_confirm: 'Are you sure you want to permanently delete shop ? This action cannot be undone.',
    shop_name: 'Shop Name',
    location: 'Location',
    manager: 'Manager',
    select_manager: 'Select Manager',
    change_status: 'Change Status',
    maintenance: 'Maintenance',
    inactive: 'Inactive',

    // ===== ROLES & PERMISSIONS =====
    roles: 'Roles',
    permissions: 'Permissions',
    add_role: 'Add role',
    edit_role: 'Edit role',
    create_role: 'Create role',
    delete_role: 'Delete role',
    delete_role_confirm: 'Are you sure you want to delete role ?',
    role_name: 'Role name',
    display_name: 'Display name',
    description: 'Description',
    users_count: 'Users count',
    manage_permissions: 'Manage permissions',
    search_roles: 'Search roles...',
    no_roles: 'No roles found',
    add_permission: 'Add permission',
    edit_permission: 'Edit permission',
    create_permission: 'Create permission',
    delete_permission: 'Delete permission',
    delete_permission_confirm: 'Are you sure you want to delete permission ?',
    permission_name: 'Permission name',
    search_permissions: 'Search permissions...',
    no_permissions: 'No permissions found',
    save: 'Save',
    update: 'Update',
    create: 'Create',
    cancel: 'Cancel',

    // ===== AUDIT TRAIL =====
    audit_trail: 'Audit Trail',
    date_time: 'Date & Time',
    user: 'User',
    action: 'Action',
    module: 'Module',
    total_entries: 'Total Entries',
    today: 'Today',
    this_week: 'This Week',
    unique_modules: 'Unique Modules',
    all_modules: 'All Modules',
    all_actions: 'All Actions',
    user_email: 'User Email',
    enter_user_email: 'Enter user email',
    search_in_audit: 'Search in audit...',

    // ===== FAILED LOGINS =====
    failed_logins: 'Failed Login Attempts',
    total_records: 'Total Records',
    unique_emails: 'Unique Emails',
    unique_ips: 'Unique IPs',
    blocked_ips: 'Blocked IPs',
    today_attempts: "Today's Attempts",
    attempts: 'Attempts',
    last_attempt: 'Last Attempt',
    blocked: 'Blocked',
    block_ip: 'Block IP',
    unblock_ip: 'Unblock IP',
    clear_attempts: 'Clear Attempts',
    clear_all: 'Clear All',
    clear_email_confirm: 'Are you sure you want to clear all attempts for ?',
    clear_all_confirm: 'Are you sure you want to clear all failed login attempts?',
    block_ip_confirm: 'Are you sure you want to block IP ?',
    unblock_ip_confirm: 'Are you sure you want to unblock IP ?',

    // ===== COMPANIES =====
    companies: 'Companies',
    add_company: 'Add Company',
    edit_company: 'Edit Company',
    delete_company: 'Delete Company',
    delete_company_confirm: 'Are you sure you want to delete company?',
    restore_company: 'Restore Company',
    restore_company_confirm: 'Are you sure you want to restore company ?',
    force_delete_company: 'Permanently Delete Company',
    force_delete_company_confirm: 'Are you sure you want to permanently delete company? This action cannot be undone.',
    activate_company_confirm: 'Are you sure you want to activate company ?',
    deactivate_company_confirm: 'Are you sure you want to deactivate company ?',
    company_name: 'Company Name',
    address: 'Address',
    trashed: 'Trashed',
    actions: 'Actions',
    edit: 'Edit',
    force_delete: 'Force Delete',
    delete: 'Delete',
    confirm: 'Confirm',
    access_denied: 'Access Denied',
    you_do_not_have_permission: 'You do not have permission to view companies.',

    // ===== USERS =====
    users: 'Users',
    create_user: 'Create user',
    edit_user: 'Edit user',
    delete_user: 'Delete user',
    delete_user_confirm: 'Are you sure you want to delete user ?',
    default_password: 'Default password',
    verify_user: 'Verify User',
    verified_col: 'Verified',
    activate: 'Activate',
    deactivate: 'Deactivate',
    suspend: 'Suspend',
    assign_role: 'Assign role',
    assign_role_to: 'Assign role to',
    reset_password_for: 'Reset password for',
    verify_now: 'Verify now',
    suspended: 'Suspended',
    yes: 'Yes',
    no: 'No',
    select_role: '-- Select role --',

    // ===== OTP MANAGEMENT =====
    otp_management: 'OTP Management',
    type: 'Type',
    used: 'Used',
    unused: 'Unused',
    expired: 'Expired',
    expires_at: 'Expires At',
    enter_email: 'Enter email',
    all_types: 'All Types',
    all_status: 'All Status',
    cleanup_expired: 'Cleanup Expired',
    cleanup_used: 'Cleanup Used OTPs',
    cleanup_expired_confirm: 'Are you sure you want to delete all expired OTP records?',
    cleanup_used_confirm: 'Are you sure you want to delete all used OTP records older than 30 days?',

    // ===== PRODUCTS =====
    products: 'Products',
    add_product: 'Add Product',
    edit_product: 'Edit Product',
    delete_product: 'Delete Product',
    delete_product_confirm: 'Are you sure you want to delete product with IMEI {imei}?',
    restore_product: 'Restore Product',
    restore_product_confirm: 'Are you sure you want to restore product with IMEI {imei}?',
    force_delete_product: 'Permanently Delete Product',
    force_delete_product_confirm: 'Are you sure you want to permanently delete product with IMEI {imei}? This action cannot be undone.',
    change_product_status: 'Change Product Status',
    current_status: 'Current status',
    no_loan_prices_added: 'No loan prices added yet.',
    in_stock: 'In Stock',
    transferred: 'Transferred',
    received: 'Received',
    returned: 'Returned',
    select_sku: 'Select SKU',
    select_company: 'Select Company',
    select_category_first: 'Please select a category first',
    no_skus_for_category: 'No SKUs available for this category',
    imei_list: 'IMEI List',
    add_imei: 'Add IMEI',
    scan: 'Scan',
    single_imei: 'Single IMEI',
    pricing: 'Pricing',
    basic_information: 'Basic Information',
    purchase_info: 'Purchase Info',
    unit_price: 'Unit Price',
    purchased: 'Purchased',
    added: 'Added',
    available: 'Available',
    no_more_items: 'No more items available',
    show_purchase_history: 'Show purchase history',
    hide_history: 'Hide history',
    auto_filled: 'Auto-filled',
    enter_imei_manually: 'Enter IMEI manually',
    please_enter_imei: 'Please enter an IMEI',
    imei_already_exists: 'IMEI "{imei}" already exists in the list',
    imei_added: 'IMEI "{imei}" added',
    imei_updated: 'IMEI updated to "{imei}"',
    imei_scanned_and_added: 'IMEI "{imei}" scanned and added',
    product_updated_successfully: 'Product updated successfully',
    products_created: 'Products created successfully',
    stop_scanner: 'Stop Scanner',
    scanner_init_error: 'Scanner initialisation error',
    could_not_start_camera: 'Could not start camera',
    camera_permission_denied: 'Camera permission denied. Please allow camera access in your browser settings.',
    no_camera_found: 'No camera found on this device.',
    scanner_element_not_found: 'Scanner element not found. Please try again.',
    duplicate_imei_warning: 'IMEI "{imei}" already exists in the list',
    select_status: 'Select Status',

    // ===== ANALYSIS PAGE =====
    analysis_dashboard: 'Analysis Dashboard',
    daily_trend_30d: 'Daily Trend (30d)',
    weekly_trend: 'Weekly Trend',
    monthly_trend: 'Monthly Trend',
    revenue_by_category: 'Revenue by Category',
    top_agents_by_revenue: 'Top Agents by Revenue',
    top_shops_by_revenue: 'Top Shops by Revenue',
    top_products_by_revenue: 'Top Products by Revenue',
    top_models_by_revenue: 'Top Models by Revenue',
    profit_trends: 'Profit Trends',
    interest_summary: 'Interest Summary',
    total_loan_sales: 'Total Loan Sales',
    total_loan_revenue: 'Total Loan Revenue',
    interest_earned: 'Interest Earned',
    total_cash_sales: 'Total Cash Sales',
    total_cash_revenue: 'Total Cash Revenue',
    total_stock_cost: 'Total Stock Cost',
    stock_summary: 'Stock Summary',
    agent_ranking_by_sales: 'Agent Ranking by Sales',
    rank: 'Rank',
    loading_analysis: 'Loading analysis...',
    error_loading_analysis: 'Error loading analysis',
  },

  zh: {
    // ===== GENERAL =====
    app_name: 'IMS',
    dashboard: '仪表板',
    logged_in_as: '登录为',
    register_user: '注册用户',
    admins: '管理员',
    suppliers: '供应商',
    customers: '客户',
    deliveries: '配送员',
    orders: '订单',
    revenue: '收入',
    stock: '库存',
    cart: '购物车',
    my_orders: '我的订单',
    logout: '退出',
    login: '登录',
    email: '电子邮件',
    password: '密码',
    demo: '演示 — 选择账户',
    checkout_success: '您的订单已收到。您可以在下方跟踪其状态。',
    total: '总计',
    delivery_fee: '配送费',
    confirm_order: '确认订单',
    search: '搜索产品...',
    add_to_cart: '加入购物车',
    add_more: '再加',
    order_status: '订单状态',
    order_id: '订单 #',
    rider: '配送员',
    no_orders: '您还没有订单。',
    paid: '已支付',
    unpaid: '未支付',
    pending_approval: '待批准',
    active: '活跃',
    deleted: '已删除',
    approve: '批准',
    completed: '已完成',
    in_progress: '进行中',
    status_steps: ['已接收', '准备中', '配送中', '已送达'] as any,
    forgot_password: '忘记密码？',
    reset_password: '重置密码',
    enter_email_reset: '输入您的电子邮件以接收密码重置链接。',
    send_reset_link: '发送重置链接',
    back_to_login: '返回登录',
    reset_link_sent: '密码重置链接已发送到您的电子邮件。',
    overview_title: '仪表板',
    recent_activity: '最近活动',
    total_revenue: '总收入',
    all_orders: '所有订单',
    active_suppliers: '活跃供应商',
    total_deliveries: '配送员',
    suppliers_count: '供应商',
    customers_count: '客户',
    pending_approval_count: '待批准',
    paid_orders: '已支付订单',
    unpaid_orders: '未支付订单',
    avg_order_value: '平均订单额',
    assigned_orders: '已分配订单',
    completed_orders: '已完成',
    ongoing_orders: '进行中',
    register_title: '注册新用户',
    user_type: '用户类型',
    full_name: '全名',
    register_btn: '注册用户',
    register_success: '用户已注册。登录详情将发送到他们的电子邮件。',
    name_col: '姓名',
    email_col: '电子邮件',
    role_col: '角色',
    status_col: '状态',
    phone_col: '电话',
    orders_count_col: '订单数',
    total_spent_col: '总花费',
    action_col: '操作',
    order_number_col: '订单号',
    customer_col: '客户',
    amount_col: '金额',
    payment_col: '支付',
    rider_col: '配送员',
    admins_title: '管理员（管理员、经理和会计）',
    suppliers_title: '供应商',
    deliveries_title: '配送员',
    assigned_orders_col: '已分配订单',
    completed_deliveries_col: '已完成',
    customers_title: '客户',
    orders_title: '所有订单',
    my_orders_title: '我的订单',
    revenue_title: '收入报告',
    revenue_total: '总收入（已支付）',
    revenue_paid: '已支付订单',
    revenue_unpaid: '未支付订单',
    revenue_chart_title: '过去6个月的收入',
    revenue_month: '月份',
    revenue_amount: '收入',
    shop_title: '商店 — 所有产品',
    cart_title: '我的购物车',
    cart_empty: '您的购物车是空的。',
    customer_orders_title: '我的订单',
    customer_no_orders: '您还没有订单。',
    users_title: '用户列表',
    add_user: '添加用户',
    close: '关闭',
    self_register: '注册为客户',
    register_customer_title: '注册为客户',
    phone: '电话号码',
    register: '注册',
    already_have_account: '已有账户？登录',
    customer_registered: '注册成功。您正在登录...',
    search_table: '搜索...',
    previous: '上一页',
    next: '下一页',
    refresh: '刷新',
    showing: '显示',
    of: '共',
    entries: '条',
    no_results: '没有结果',
    or_continue_with: '或继续使用',
    signin_google: '使用 Google 登录',
    signin_apple: '使用 Apple 登录',
    items_per_page: '每页条数',
    settings: '设置', // ✅ Chinese

    // ===== DASHBOARD CARDS & CHARTS =====
    total_users: '总用户',
    total_shops: '总店铺',
    products_in_stock: '库存产品',
    total_sales: '总销售',
    total_companies: '总公司',
    returned_devices: '退货设备',
    products_by_category: '按分类的产品',
    products_by_status: '按状态的产品',
    sales_by_payment_method: '按支付方式的销售',
    top_selling_products: '畅销产品',
    sales_trend_30_days: '销售趋势（最近30天）',
    sales_by_month: '每月销售',
    product: '产品',
    count: '数量',
    total_amount: '总金额',
    loading_dashboard: '加载仪表板...',
    error_loading_dashboard: '加载仪表板出错',
    retry: '重试',

    // ===== SALES PAGE =====
    sales: '销售',
    sales_history: '销售历史',
    all_statuses: '所有状态',
    filter_by_status: '按状态筛选',
    make_sale: '创建销售',
    sku: 'SKU',
    imei: 'IMEI',
    shop: '店铺',
    payment_method: '付款方式',
    cash: '现金',
    loan: '贷款',
    loan_price: '贷款价格',
    select_loan_price: '选择贷款价格',
    no_loan_prices: '没有贷款价格',
    discount_amount: '折扣金额',
    confirm_sale: '确认销售',
    product_details: '产品详情',
    cash_selling_price: '现金售价',
    loan_selling_prices: '贷款售价',
    status: '状态',
    stock_status: '库存状态',
    agent: '代理人',
    company: '公司',
    cancellation_reason: '取消原因',
    created_at: '创建时间',
    cancel_sale: '取消销售',
    restore: '恢复',
    provide_cancellation_reason: '请提供取消原因',
    enter_reason: '输入原因',
    confirm_cancel: '确认取消',
    analysis: '分析',

    // ===== REPORTS PAGE =====
    reports: '报告',
    export_csv: '导出 CSV',
    export_excel: '导出 Excel',
    exporting: '导出中...',
    sales_report: '销售报告',
    stock_report: '库存报告',
    returns_report: '退货报告',
    from_date: '开始日期',
    to_date: '结束日期',
    select_agent: '选择代理人',
    category: '分类',
    all_categories: '所有分类',
    all_shops: '所有店铺',
    all: '全部',
    select_stock_status: '选择库存状态',
    updated_at: '更新时间',
    buying_price: '采购价',
    total_profit: '总利润',
    total_products: '总产品数',
    pending_return: '待退货',
    total_returned: '总退货数',
    sold: '已售',

    // ===== PROFILE & OTP KEYS =====
    profile: '个人资料',
    edit_profile: '编辑资料',
    update_profile: '更新资料',
    change_password: '修改密码',
    current_password: '当前密码',
    new_password: '新密码',
    confirm_password: '确认密码',
    verify_otp_title: '验证 OTP',
    otp_code: 'OTP 代码',
    resend_otp: '重新发送 OTP',
    enter_otp_sent: '输入发送到以下地址的 OTP 代码：',
    enter_otp_and_new_password: '输入 OTP 代码和新密码',
    verify: '验证',
    loading: '加载中...',
    verified: '已验证',
    pending: '待验证',
    creating: '创建中...',
    updating: '更新中...',

    // ===== PRODUCT CATEGORIES =====
    product_categories: '产品分类',
    add_category: '添加分类',
    edit_category: '编辑分类',
    delete_category: '删除分类',
    delete_category_confirm: '您确定要删除分类  吗？',
    category_name: '分类名称',
    model: '型号',
    enter_sku: '输入 SKU',
    add: '添加',
    toggle_status: '切换状态',
    activate_category_confirm: '您确定要激活分类  吗？',
    deactivate_category_confirm: '您确定要停用分类  吗？',

    // ===== SHOPS =====
    shops: '店铺',
    add_shop: '添加店铺',
    edit_shop: '编辑店铺',
    create_shop: '创建店铺',
    delete_shop: '删除店铺',
    delete_shop_confirm: '您确定要删除店铺  吗？',
    restore_shop: '恢复店铺',
    restore_shop_confirm: '您确定要恢复店铺  吗？',
    force_delete_shop: '永久删除店铺',
    force_delete_shop_confirm: '您确定要永久删除店铺  吗？此操作不可撤销。',
    shop_name: '店铺名称',
    location: '位置',
    manager: '经理',
    select_manager: '选择经理',
    change_status: '更改状态',
    maintenance: '维护中',
    inactive: '未激活',

    // ===== ROLES & PERMISSIONS =====
    roles: '角色',
    permissions: '权限',
    add_role: '添加角色',
    edit_role: '编辑角色',
    create_role: '创建角色',
    delete_role: '删除角色',
    delete_role_confirm: '您确定要删除角色  吗？',
    role_name: '角色名称',
    display_name: '显示名称',
    description: '描述',
    users_count: '用户数',
    manage_permissions: '管理权限',
    search_roles: '搜索角色...',
    no_roles: '未找到角色',
    add_permission: '添加权限',
    edit_permission: '编辑权限',
    create_permission: '创建权限',
    delete_permission: '删除权限',
    delete_permission_confirm: '您确定要删除权限  吗？',
    permission_name: '权限名称',
    search_permissions: '搜索权限...',
    no_permissions: '未找到权限',
    save: '保存',
    update: '更新',
    create: '创建',
    cancel: '取消',

    // ===== AUDIT TRAIL =====
    audit_trail: '审计跟踪',
    date_time: '日期和时间',
    user: '用户',
    action: '操作',
    module: '模块',
    total_entries: '总记录数',
    today: '今天',
    this_week: '本周',
    unique_modules: '独特模块',
    all_modules: '所有模块',
    all_actions: '所有操作',
    user_email: '用户邮箱',
    enter_user_email: '输入用户邮箱',
    search_in_audit: '在审计记录中搜索...',

    // ===== FAILED LOGINS =====
    failed_logins: '失败登录尝试',
    total_records: '总记录',
    unique_emails: '唯一邮箱',
    unique_ips: '唯一 IP',
    blocked_ips: '已封锁 IP',
    today_attempts: '今日尝试',
    attempts: '尝试次数',
    last_attempt: '上次尝试',
    blocked: '已封锁',
    block_ip: '封锁 IP',
    unblock_ip: '解除封锁 IP',
    clear_attempts: '清除尝试',
    clear_all: '全部清除',
    clear_email_confirm: '您确定要清除  的所有尝试吗？',
    clear_all_confirm: '您确定要清除所有失败登录尝试记录吗？',
    block_ip_confirm: '您确定要封锁 IP 吗？',
    unblock_ip_confirm: '您确定要解除 IP  的封锁吗？',

    // ===== COMPANIES =====
    companies: '公司',
    add_company: '添加公司',
    edit_company: '编辑公司',
    delete_company: '删除公司',
    delete_company_confirm: '您确定要删除公司  吗？',
    restore_company: '恢复公司',
    restore_company_confirm: '您确定要恢复公司  吗？',
    force_delete_company: '永久删除公司',
    force_delete_company_confirm: '您确定要永久删除公司  吗？此操作不可撤销。',
    activate_company_confirm: '您确定要激活公司 吗？',
    deactivate_company_confirm: '您确定要停用公司 吗？',
    company_name: '公司名称',
    address: '地址',
    trashed: '已删除',
    edit: '编辑',
    force_delete: '强制删除',
    delete: '删除',
    confirm: '确认',
    access_denied: '访问被拒绝',
    you_do_not_have_permission: '您没有权限查看公司。',

    // ===== USERS =====
    users: '用户',
    create_user: '创建用户',
    edit_user: '编辑用户',
    delete_user: '删除用户',
    delete_user_confirm: '您确定要删除用户  吗？',
    default_password: '默认密码',
    verify_user: '验证用户',
    verified_col: '已验证',
    activate: '启用',
    deactivate: '停用',
    suspend: '暂停',
    assign_role: '分配角色',
    assign_role_to: '分配角色给',
    reset_password_for: '重置密码为',
    verify_now: '立即验证',
    suspended: '已暂停',
    yes: '是',
    no: '否',
    select_role: '-- 选择角色 --',

    // ===== OTP MANAGEMENT =====
    otp_management: 'OTP 管理',
    type: '类型',
    used: '已使用',
    unused: '未使用',
    expired: '已过期',
    expires_at: '过期时间',
    enter_email: '输入邮箱',
    all_types: '所有类型',
    all_status: '所有状态',
    cleanup_expired: '清理已过期的',
    cleanup_used: '清理已使用的 OTP',
    cleanup_expired_confirm: '您确定要删除所有已过期的 OTP 记录吗？',
    cleanup_used_confirm: '您确定要删除所有超过 30 天的已使用 OTP 记录吗？',

    // ===== PRODUCTS =====
    products: '产品',
    add_product: '添加产品',
    edit_product: '编辑产品',
    delete_product: '删除产品',
    delete_product_confirm: '您确定要删除 IMEI 为 {imei} 的产品吗？',
    restore_product: '恢复产品',
    restore_product_confirm: '您确定要恢复 IMEI 为 {imei} 的产品吗？',
    force_delete_product: '永久删除产品',
    force_delete_product_confirm: '您确定要永久删除 IMEI 为 {imei} 的产品吗？此操作不可撤销。',
    change_product_status: '更改产品状态',
    current_status: '当前状态',
    no_loan_prices_added: '尚未添加贷款价格。',
    in_stock: '有库存',
    transferred: '已调拨',
    received: '已收货',
    returned: '已退货',
    select_sku: '选择 SKU',
    select_company: '选择公司',
    select_category_first: '请先选择分类',
    no_skus_for_category: '该分类没有可用的 SKU',
    imei_list: 'IMEI 列表',
    add_imei: '添加 IMEI',
    scan: '扫描',
    single_imei: '单个 IMEI',
    pricing: '定价',
    basic_information: '基本信息',
    purchase_info: '采购信息',
    unit_price: '单价',
    purchased: '已采购',
    added: '已添加',
    available: '可用',
    no_more_items: '没有更多可用商品',
    show_purchase_history: '显示采购历史',
    hide_history: '隐藏历史',
    auto_filled: '自动填充',
    enter_imei_manually: '手动输入 IMEI',
    please_enter_imei: '请输入 IMEI',
    imei_already_exists: 'IMEI "{imei}" 已存在于列表中',
    imei_added: 'IMEI "{imei}" 已添加',
    imei_updated: 'IMEI 已更新为 "{imei}"',
    imei_scanned_and_added: 'IMEI "{imei}" 已扫描并添加',
    product_updated_successfully: '产品更新成功',
    products_created: '产品创建成功',
    stop_scanner: '停止扫描',
    scanner_init_error: '扫描器初始化错误',
    could_not_start_camera: '无法启动相机',
    camera_permission_denied: '相机权限被拒绝。请在浏览器设置中允许相机访问。',
    no_camera_found: '在此设备上未找到相机。',
    scanner_element_not_found: '未找到扫描器元素。请重试。',
    duplicate_imei_warning: 'IMEI "{imei}" 已存在于列表中',
    select_status: '选择状态',

    // ===== ANALYSIS PAGE =====
    analysis_dashboard: '分析仪表板',
    daily_trend_30d: '每日趋势 (30天)',
    weekly_trend: '每周趋势',
    monthly_trend: '每月趋势',
    revenue_by_category: '按类别的收入',
    top_agents_by_revenue: '按收入排名靠前的代理人',
    top_shops_by_revenue: '按收入排名靠前的店铺',
    top_products_by_revenue: '按收入排名靠前的产品',
    top_models_by_revenue: '按收入排名靠前的型号',
    profit_trends: '利润趋势',
    interest_summary: '利息摘要',
    total_loan_sales: '贷款销售总数',
    total_loan_revenue: '贷款收入总额',
    interest_earned: '已赚利息',
    total_cash_sales: '现金销售总数',
    total_cash_revenue: '现金收入总额',
    total_stock_cost: '总库存成本',
    stock_summary: '库存摘要',
    agent_ranking_by_sales: '代理人销售排名',
    rank: '排名',
    loading_analysis: '正在加载分析...',
    error_loading_analysis: '加载分析时出错',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const getStoredLanguage = (): Language => {
    const stored = localStorage.getItem('app_language');
    if (stored === 'sw' || stored === 'en' || stored === 'zh') {
      return stored;
    }
    return 'sw'; // default – change to 'en' for English or 'zh' for Chinese
  };

  const [lang, setLang] = useState<Language>(getStoredLanguage);

  useEffect(() => {
    localStorage.setItem('app_language', lang);
  }, [lang]);

  const t = (key: string): string => {
    const value = translations[lang][key];
    return value !== undefined ? value : key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
};